#!/bin/bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  bash run_cold_storage_mirroring.sh [--apply] <manifest_tsv> <cold_root>

Behavior:
  - By default this runs in rsync dry-run mode.
  - Use --apply to perform the actual copy.
  - The manifest must be a TSV generated by the workflow at
    transfer/<output_prefix>/cold_storage_paths.tsv.
  - Each listed local path is mirrored into <cold_root>/<relative_subpath>.

Examples:
  bash run_cold_storage_mirroring.sh transfer/defaults/cold_storage_paths.tsv /Volumes/cold_storage/project_a
  bash run_cold_storage_mirroring.sh --apply transfer/defaults/cold_storage_paths.tsv /Volumes/cold_storage/project_a
EOF
}

APPLY=false
if [[ "${1:-}" == "--apply" ]]; then
    APPLY=true
    shift
fi

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

if [[ $# -ne 2 ]]; then
    usage >&2
    exit 1
fi

MANIFEST_TSV="${1}"
COLD_ROOT="${2}"

if [[ ! -f "${MANIFEST_TSV}" ]]; then
    echo "Error: manifest does not exist: ${MANIFEST_TSV}" >&2
    exit 1
fi

mkdir -p "${COLD_ROOT}"

RSYNC_ARGS=(
    -avh
    --human-readable
)

if rsync --version 2>/dev/null | head -n 1 | grep -Eq 'version 3\.'; then
    RSYNC_ARGS+=(--info=progress2)
else
    RSYNC_ARGS+=(--progress)
fi

if [[ "${APPLY}" == false ]]; then
    RSYNC_ARGS+=(--dry-run)
    echo "Preview mode only. Re-run with --apply to perform the mirroring."
fi

echo "Manifest:      ${MANIFEST_TSV}"
echo "Cold storage:  ${COLD_ROOT}"

{
    read -r _
    while IFS=$'\t' read -r kind category local_path relative_subpath; do
        [[ -z "${kind}" ]] && continue
        target_path="${COLD_ROOT}/${relative_subpath}"
        if [[ "${kind}" == "dir" ]]; then
            if [[ -d "${local_path}" ]]; then
                mkdir -p "${target_path}"
                echo "Mirroring directory: ${local_path} -> ${target_path}"
                rsync "${RSYNC_ARGS[@]}" "${local_path}/" "${target_path}/"
            else
                echo "Skipping missing directory: ${local_path}" >&2
            fi
        else
            if [[ -f "${local_path}" ]]; then
                mkdir -p "$(dirname "${target_path}")"
                echo "Mirroring file: ${local_path} -> ${target_path}"
                rsync "${RSYNC_ARGS[@]}" "${local_path}" "${target_path}"
            else
                echo "Skipping missing file: ${local_path}" >&2
            fi
        fi
    done
} < "${MANIFEST_TSV}"
