"""
Generate helper scripts to mirror external storage paths between local and cluster.

The scripts preserve the local storage layout beneath a configurable cluster root
such as /lfs/aokid, so a local path like /Data/WGS/project/ref becomes
/lfs/aokid/Data/WGS/project/ref on the cluster.

Config keys used:
- transfer.cluster_storage_root
- storage.reference.dir
- storage.bam.ingroup_dir
- storage.bam.outgroup_dir
- reads.ingroup_dir
- reads.ingroup_metadata
"""

from pathlib import Path

TRANSFER_DIR = f"transfer/{output_prefix}"
TRANSFER_MANIFEST = f"{TRANSFER_DIR}/external_paths.tsv"
TRANSFER_UPLOAD_SCRIPT = f"{TRANSFER_DIR}/sync_local_external_to_cluster.sh"
TRANSFER_DOWNLOAD_SCRIPT = f"{TRANSFER_DIR}/sync_cluster_external_to_local.sh"
PROJECT_OUTPUT_MANIFEST = f"{TRANSFER_DIR}/project_output_paths.tsv"
PROJECT_OUTPUT_DOWNLOAD_SCRIPT = f"{TRANSFER_DIR}/sync_cluster_project_outputs_to_local.sh"
COLD_STORAGE_MANIFEST = f"{TRANSFER_DIR}/cold_storage_paths.tsv"


def _shell_quote(value: str) -> str:
    return "'" + str(value).replace("'", "'\"'\"'") + "'"


def _transfer_items():
    items = []
    for path in external_transfer_directories():
        items.append({
            "kind": "dir",
            "category": "external_storage_dir",
            "local_path": str(Path(path)),
            "remote_subpath": remote_mirror_subpath(path),
            "remote_path": remote_mirror_path(path),
        })
    for path in external_ingroup_fastq_files():
        items.append({
            "kind": "file",
            "category": "ingroup_fastq",
            "local_path": str(Path(path)),
            "remote_subpath": remote_mirror_subpath(path),
            "remote_path": remote_mirror_path(path),
        })
    items.sort(key=lambda x: (x["kind"], x["local_path"]))
    return items


def _project_output_items():
    items = []
    for relative_path in ("results", "figures", "logs"):
        local_path = PROJECT_ROOT / relative_path
        items.append({
            "kind": "dir",
            "category": "project_output_dir",
            "local_path": str(local_path),
            "remote_subpath": relative_path,
        })
    return items


def _cold_storage_relative_subpath(path):
    if not LOCAL_STORAGE_ROOT:
        return None
    candidate = Path(str(path)).expanduser()
    try:
        relative = candidate.relative_to(Path(LOCAL_STORAGE_ROOT))
    except ValueError:
        return None
    return str(relative)


def _cold_storage_items():
    items = []
    for item in _transfer_items():
        relative_subpath = _cold_storage_relative_subpath(item["local_path"])
        if not relative_subpath:
            continue
        items.append({
            "kind": item["kind"],
            "category": item["category"],
            "local_path": item["local_path"],
            "relative_subpath": relative_subpath,
        })
    items.sort(key=lambda x: (x["kind"], x["local_path"]))
    return items


def _rsync_script_header(remote_usage_line=None, root_assignment=None, default_comment=None):
    header = [
        "#!/bin/bash",
        "set -euo pipefail",
        "",
    ]
    if remote_usage_line:
        header.extend([
            'REMOTE="${1:-${CLUSTER_REMOTE:-}}"',
            root_assignment,
            'CLUSTER_PORT="${CLUSTER_PORT:-}"',
            'if [ -z "$REMOTE" ]; then',
            f'  echo "{remote_usage_line}" >&2',
            "  exit 1",
            "fi",
            'if [ -n "$CLUSTER_PORT" ]; then',
            '  SSH_CMD=(ssh -p "$CLUSTER_PORT")',
            '  RSYNC_CMD=(rsync -e "ssh -p $CLUSTER_PORT")',
            "else",
            '  SSH_CMD=(ssh)',
            '  RSYNC_CMD=(rsync)',
            "fi",
            "",
        ])
    else:
        header.extend([
            root_assignment,
            'if [ -z "$COLD_STORAGE_ROOT" ]; then',
            '  echo "Usage: $0 [cold_storage_root]" >&2',
            '  echo "Or set COLD_STORAGE_ROOT." >&2',
            "  exit 1",
            "fi",
            'RSYNC_CMD=(rsync)',
            "",
        ])
    header.extend([
        f'# Generated by gbs_pipeline for output_prefix="{output_prefix}"',
    ])
    if default_comment:
        header.append(default_comment)
    header.append("")
    return header


rule generate_external_transfer_scripts:
    """
    Write a manifest of external storage paths plus upload/download helper
    scripts that mirror those paths between local and cluster storage roots.
    """
    output:
        manifest=TRANSFER_MANIFEST,
        upload=TRANSFER_UPLOAD_SCRIPT,
        download=TRANSFER_DOWNLOAD_SCRIPT
    run:
        items = _transfer_items()
        outdir = Path(TRANSFER_DIR)
        outdir.mkdir(parents=True, exist_ok=True)

        with open(output.manifest, "w", encoding="ascii") as handle:
            handle.write("kind\tcategory\tlocal_path\tremote_subpath\tremote_path\n")
            for item in items:
                handle.write(
                    f"{item['kind']}\t{item['category']}\t{item['local_path']}\t{item['remote_subpath']}\t{item['remote_path']}\n"
                )

        header = [
            "#!/bin/bash",
            "set -euo pipefail",
            "",
            'REMOTE="${1:-${CLUSTER_REMOTE:-}}"',
            f'CLUSTER_STORAGE_ROOT="${{2:-${{CLUSTER_STORAGE_ROOT:-{CLUSTER_STORAGE_ROOT_DEFAULT}}}}}"',
            'CLUSTER_PORT="${CLUSTER_PORT:-}"',
            'if [ -z "$REMOTE" ]; then',
            '  echo "Usage: $0 user@host [cluster_storage_root]" >&2',
            '  echo "Or set CLUSTER_REMOTE and optionally CLUSTER_STORAGE_ROOT / CLUSTER_PORT." >&2',
            "  exit 1",
            "fi",
            'if [ -n "$CLUSTER_PORT" ]; then',
            '  SSH_CMD=(ssh -p "$CLUSTER_PORT")',
            '  RSYNC_CMD=(rsync -e "ssh -p $CLUSTER_PORT")',
            "else",
            '  SSH_CMD=(ssh)',
            '  RSYNC_CMD=(rsync)',
            "fi",
            "",
            f'# Generated by gbs_pipeline for output_prefix="{output_prefix}"',
            f'# Cluster mirror root default: {CLUSTER_STORAGE_ROOT_DEFAULT}',
            "",
        ]

        upload_lines = list(header)
        upload_lines.append('echo "Syncing external files from local storage to ${REMOTE}:${CLUSTER_STORAGE_ROOT}"')
        upload_lines.append("")
        if not items:
            upload_lines.append('echo "No external storage paths configured; nothing to transfer."')
        for item in items:
            local_q = _shell_quote(item["local_path"])
            upload_remote_expr = '${CLUSTER_STORAGE_ROOT}/' + item["remote_subpath"].lstrip("/")
            if item["kind"] == "dir":
                upload_lines.extend([
                    f'if [ -d {local_q} ]; then',
                    f'  remote_path="{upload_remote_expr}"',
                    '  "${SSH_CMD[@]}" "$REMOTE" "mkdir -p \\"$remote_path\\""',
                    f'  "${{RSYNC_CMD[@]}}" -avh {local_q}/ "$REMOTE":"$remote_path"/',
                    "else",
                    f'  echo "Skipping missing directory: {item["local_path"]}" >&2',
                    "fi",
                    "",
                ])
            else:
                upload_lines.extend([
                    f'if [ -f {local_q} ]; then',
                    f'  remote_path="{upload_remote_expr}"',
                    '  remote_parent="$(dirname "$remote_path")"',
                    '  "${SSH_CMD[@]}" "$REMOTE" "mkdir -p \\"$remote_parent\\""',
                    f'  "${{RSYNC_CMD[@]}}" -avh {local_q} "$REMOTE":"$remote_path"',
                    "else",
                    f'  echo "Skipping missing file: {item["local_path"]}" >&2',
                    "fi",
                    "",
                ])

        download_lines = list(header)
        download_lines.append('echo "Syncing external files from ${REMOTE}:${CLUSTER_STORAGE_ROOT} back to local storage"')
        download_lines.append("")
        if not items:
            download_lines.append('echo "No external storage paths configured; nothing to transfer."')
        for item in items:
            local_q = _shell_quote(item["local_path"])
            remote_expr = '${CLUSTER_STORAGE_ROOT}/' + item["remote_subpath"].lstrip("/")
            if item["kind"] == "dir":
                download_lines.extend([
                    f'mkdir -p {local_q}',
                    f'remote_path="{remote_expr}"',
                    f'"${{RSYNC_CMD[@]}}" -avh "$REMOTE":"$remote_path"/ {local_q}/',
                    "",
                ])
            else:
                local_parent_q = _shell_quote(str(Path(item["local_path"]).parent))
                download_lines.extend([
                    f'mkdir -p {local_parent_q}',
                    f'remote_path="{remote_expr}"',
                    f'"${{RSYNC_CMD[@]}}" -avh "$REMOTE":"$remote_path" {local_q}',
                    "",
                ])

        Path(output.upload).write_text("\n".join(upload_lines) + "\n", encoding="ascii")
        Path(output.download).write_text("\n".join(download_lines) + "\n", encoding="ascii")
        Path(output.upload).chmod(0o755)
        Path(output.download).chmod(0o755)


rule generate_local_sync_scripts:
    """
    Write local-side helper scripts for syncing project outputs from the cluster
    and back-mirroring SSD-resident external files into cold storage.
    """
    output:
        project_manifest=PROJECT_OUTPUT_MANIFEST,
        project_download=PROJECT_OUTPUT_DOWNLOAD_SCRIPT,
        cold_manifest=COLD_STORAGE_MANIFEST
    run:
        project_items = _project_output_items()
        cold_items = _cold_storage_items()
        outdir = Path(TRANSFER_DIR)
        outdir.mkdir(parents=True, exist_ok=True)

        with open(output.project_manifest, "w", encoding="ascii") as handle:
            handle.write("kind\tcategory\tlocal_path\tremote_subpath\n")
            for item in project_items:
                handle.write(
                    f"{item['kind']}\t{item['category']}\t{item['local_path']}\t{item['remote_subpath']}\n"
                )

        with open(output.cold_manifest, "w", encoding="ascii") as handle:
            handle.write("kind\tcategory\tlocal_path\trelative_subpath\n")
            for item in cold_items:
                handle.write(
                    f"{item['kind']}\t{item['category']}\t{item['local_path']}\t{item['relative_subpath']}\n"
                )

        cluster_project_default = str(TRANSFER_CFG.get("cluster_project_dir") or "")
        project_lines = _rsync_script_header(
            remote_usage_line="Usage: $0 user@host [cluster_project_root]",
            root_assignment=(
                f'CLUSTER_PROJECT_ROOT="${{2:-${{CLUSTER_PROJECT_ROOT:-{cluster_project_default}}}}}"'
            ),
            default_comment=(
                f"# Cluster project root default: {cluster_project_default}" if cluster_project_default else "# Cluster project root default: <unset>"
            ),
        )
        project_lines.extend([
            'if [ -z "$CLUSTER_PROJECT_ROOT" ]; then',
            '  echo "Set paths.transfer.cluster_project_dir in config, pass it as the second argument, or export CLUSTER_PROJECT_ROOT." >&2',
            "  exit 1",
            "fi",
            "",
        ])
        project_lines.append('echo "Syncing project outputs from ${REMOTE}:${CLUSTER_PROJECT_ROOT} into the local project directory"')
        project_lines.append("")
        for item in project_items:
            local_q = _shell_quote(item["local_path"])
            remote_expr = '${CLUSTER_PROJECT_ROOT}/' + item["remote_subpath"].lstrip("/")
            project_lines.extend([
                f'mkdir -p {local_q}',
                f'remote_path="{remote_expr}"',
                f'"${{RSYNC_CMD[@]}}" -avh "$REMOTE":"$remote_path"/ {local_q}/',
                "",
            ])

        Path(output.project_download).write_text("\n".join(project_lines) + "\n", encoding="ascii")
        Path(output.project_download).chmod(0o755)
