"""
Generate helper scripts to mirror external storage paths between local and cluster.

The scripts preserve the local storage layout beneath a configurable cluster root
such as /lfs/aokid, so a local path like /Data/WGS/project/ref becomes
/lfs/aokid/Data/WGS/project/ref on the cluster.

Config keys used:
- transfer.cluster_storage_root
- storage.reference.dir
- storage.bam.ingroup_dir
- storage.bam.outgroup_dir
- reads.ingroup_dir
- reads.ingroup_metadata
"""

from pathlib import Path

TRANSFER_DIR = f"results/transfer/{output_prefix}"
TRANSFER_MANIFEST = f"{TRANSFER_DIR}/external_paths.tsv"
TRANSFER_UPLOAD_SCRIPT = f"{TRANSFER_DIR}/sync_local_external_to_cluster.sh"
TRANSFER_DOWNLOAD_SCRIPT = f"{TRANSFER_DIR}/sync_cluster_external_to_local.sh"


def _shell_quote(value: str) -> str:
    return "'" + str(value).replace("'", "'\"'\"'") + "'"


def _transfer_items():
    items = []
    for path in external_transfer_directories():
        items.append({
            "kind": "dir",
            "category": "external_storage_dir",
            "local_path": str(Path(path)),
            "remote_path": remote_mirror_path(path),
        })
    for path in external_ingroup_fastq_files():
        items.append({
            "kind": "file",
            "category": "ingroup_fastq",
            "local_path": str(Path(path)),
            "remote_path": remote_mirror_path(path),
        })
    items.sort(key=lambda x: (x["kind"], x["local_path"]))
    return items


rule generate_external_transfer_scripts:
    """
    Write a manifest of external storage paths plus upload/download helper
    scripts that mirror those paths between local and cluster storage roots.
    """
    output:
        manifest=TRANSFER_MANIFEST,
        upload=TRANSFER_UPLOAD_SCRIPT,
        download=TRANSFER_DOWNLOAD_SCRIPT
    run:
        items = _transfer_items()
        outdir = Path(TRANSFER_DIR)
        outdir.mkdir(parents=True, exist_ok=True)

        with open(output.manifest, "w", encoding="ascii") as handle:
            handle.write("kind\tcategory\tlocal_path\tremote_path\n")
            for item in items:
                handle.write(
                    f"{item['kind']}\t{item['category']}\t{item['local_path']}\t{item['remote_path']}\n"
                )

        header = [
            "#!/bin/bash",
            "set -euo pipefail",
            "",
            'REMOTE="${1:-${CLUSTER_REMOTE:-}}"',
            f'CLUSTER_STORAGE_ROOT="${{2:-${{CLUSTER_STORAGE_ROOT:-{CLUSTER_STORAGE_ROOT_DEFAULT}}}}}"',
            'CLUSTER_PORT="${CLUSTER_PORT:-}"',
            'if [ -z "$REMOTE" ]; then',
            '  echo "Usage: $0 user@host [cluster_storage_root]" >&2',
            '  echo "Or set CLUSTER_REMOTE and optionally CLUSTER_STORAGE_ROOT / CLUSTER_PORT." >&2',
            "  exit 1",
            "fi",
            'if [ -n "$CLUSTER_PORT" ]; then',
            '  SSH_CMD=(ssh -p "$CLUSTER_PORT")',
            '  RSYNC_SSH=(-e "ssh -p $CLUSTER_PORT")',
            "else",
            '  SSH_CMD=(ssh)',
            '  RSYNC_SSH=()',
            "fi",
            "",
            f'# Generated by gbs_pipeline for output_prefix="{output_prefix}"',
            f'# Cluster mirror root default: {CLUSTER_STORAGE_ROOT_DEFAULT}',
            "",
        ]

        upload_lines = list(header)
        upload_lines.append('echo "Syncing external files from local storage to ${REMOTE}:${CLUSTER_STORAGE_ROOT}"')
        upload_lines.append("")
        if not items:
            upload_lines.append('echo "No external storage paths configured; nothing to transfer."')
        for item in items:
            local_q = _shell_quote(item["local_path"])
            upload_remote_expr = '${CLUSTER_STORAGE_ROOT}/' + item["local_path"].lstrip("/")
            if item["kind"] == "dir":
                upload_lines.extend([
                    f'if [ -d {local_q} ]; then',
                    f'  remote_path="{upload_remote_expr}"',
                    '  "${SSH_CMD[@]}" "$REMOTE" "mkdir -p \\"$remote_path\\""',
                    f'  rsync "${{RSYNC_SSH[@]}}" -avh {local_q}/ "$REMOTE":"$remote_path"/',
                    "else",
                    f'  echo "Skipping missing directory: {item["local_path"]}" >&2',
                    "fi",
                    "",
                ])
            else:
                upload_lines.extend([
                    f'if [ -f {local_q} ]; then',
                    f'  remote_path="{upload_remote_expr}"',
                    '  remote_parent="$(dirname "$remote_path")"',
                    '  "${SSH_CMD[@]}" "$REMOTE" "mkdir -p \\"$remote_parent\\""',
                    f'  rsync "${{RSYNC_SSH[@]}}" -avh {local_q} "$REMOTE":"$remote_path"',
                    "else",
                    f'  echo "Skipping missing file: {item["local_path"]}" >&2',
                    "fi",
                    "",
                ])

        download_lines = list(header)
        download_lines.append('echo "Syncing external files from ${REMOTE}:${CLUSTER_STORAGE_ROOT} back to local storage"')
        download_lines.append("")
        if not items:
            download_lines.append('echo "No external storage paths configured; nothing to transfer."')
        for item in items:
            local_q = _shell_quote(item["local_path"])
            remote_expr = '${CLUSTER_STORAGE_ROOT}/' + item["local_path"].lstrip("/")
            if item["kind"] == "dir":
                download_lines.extend([
                    f'mkdir -p {local_q}',
                    f'remote_path="{remote_expr}"',
                    f'rsync "${{RSYNC_SSH[@]}}" -avh "$REMOTE":"$remote_path"/ {local_q}/',
                    "",
                ])
            else:
                local_parent_q = _shell_quote(str(Path(item["local_path"]).parent))
                download_lines.extend([
                    f'mkdir -p {local_parent_q}',
                    f'remote_path="{remote_expr}"',
                    f'rsync "${{RSYNC_SSH[@]}}" -avh "$REMOTE":"$remote_path" {local_q}',
                    "",
                ])

        Path(output.upload).write_text("\n".join(upload_lines) + "\n", encoding="ascii")
        Path(output.download).write_text("\n".join(download_lines) + "\n", encoding="ascii")
        Path(output.upload).chmod(0o755)
        Path(output.download).chmod(0o755)
